### ISSUE TITLE
Media library folders looks strange and inconvenient in Content Editor

### ISSUE THREAD

**Issue by Antonytm** [ugo-quaisse/sitecore-author-toolbox#1]
**Describe the bug**
Extension makes media library item folders looks strange and inconvenient

**To Reproduce**
1. Install extension to Google Chrome
2. Login to Sitecore
3. Open Content Editor
4. Open any folder in Medial Library

**Actual behavior**
Media library folder items works become more inconvenient with this plugin. Big dropdown area that force valuable data to move lower. It is very inconvenient on small screens.
**Expected behavior**
Media library folder items should look not worse than before

**Screenshots**
![image](https://user-images.githubusercontent.com/647813/79883998-407b2c00-83fd-11ea-9c84-2eb9f5aefc28.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.163

**Comment by ugo-quaisse** [comment]
Thanks Antonytm for your feedback,
It should not be the case for media items, the drag and drop section should be visible only for folder. It will be fixed in the next release,

**Comment by ugo-quaisse** [comment]
Hey @Antonytm, an update with this fix has been rolled out (v2.0.3). I changed the behavior of this option by replacing the Iframe with a button that opens a modal box.

Let me know id you are still facing an issue
