### ISSUE TITLE
Launchpad UI does not load after selecting and saving it from extension

### ISSUE THREAD

**Issue by isaadansari** [ugo-quaisse/sitecore-author-toolbox#12]
**Describe the bug**
Launchpad UI does not load after selecting and saving it from extension

**To Reproduce**
1. Go to 'Sitecore author toolbox' extension
2. Click on 'Launchpad UI'
3. Save settings
4. Now go to your Sitecore Launchpad and See error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome, safari]
 - Version [2.2.3]

**Comment by ugo-quaisse** [comment]
Should be solved after 2.3.4 update, can you please confirm?
