### ISSUE TITLE
Icons are overlapping in the content editor

### ISSUE THREAD

**Issue by isaadansari** [ugo-quaisse/sitecore-author-toolbox#13]
**Describe the bug**
Icons are overlapping in the content editor

**To Reproduce**
1. Go to 'Content Editor'

**Expected behavior**
the text should not hide

**Screenshots**
https://www.screencast.com/t/3tgWXYMKe

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by ugo-quaisse** [comment]
Fix with https://github.com/ugo-quaisse/sitecore-author-toolbox/commit/8ecce952600516994fedc07fef5891c88d877cb2

**Comment by ugo-quaisse** [comment]
Fix with latest commit https://github.com/ugo-quaisse/sitecore-author-toolbox/commit/c9ded34cba14a82c784df604a38a4bc1a39b6f41
