### ISSUE TITLE
Unnecessary arrow icons

### ISSUE THREAD

**Issue by isaadansari** [ugo-quaisse/sitecore-author-toolbox#14]
**Describe the bug**
Unnecessary arrow icons

**To Reproduce**
1. Go to 'Content Editor'
2. Click on media library
3. Switch to Listing 

**Expected behavior**
Unnecessary arrow icons, should not be there

**Screenshots**
https://www.screencast.com/t/pRwDnQEPFL

**Desktop (please complete the following information):**
 - OS:windows
 - Browser chrome

**Comment by ugo-quaisse** [comment]
Fix with https://github.com/ugo-quaisse/sitecore-author-toolbox/commit/8ecce952600516994fedc07fef5891c88d877cb2
