### ISSUE TITLE
On click on Media Library, it should show images list

### ISSUE THREAD

**Issue by isaadansari** [ugo-quaisse/sitecore-author-toolbox#15]
**Describe the bug**
On click on Media Library, it should show images list instead of Search.

**To Reproduce**
1. Go to 'Content Editor'
2. Click on Media Library'
4. See behaviour

**Expected behavior**
On click on Media Library, it should show images list instead of Search. 

**Screenshots**
https://www.screencast.com/t/BBS0Sj5rED

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by ugo-quaisse** [comment]
Fix with latest commit https://github.com/ugo-quaisse/sitecore-author-toolbox/commit/c9ded34cba14a82c784df604a38a4bc1a39b6f41
