### ISSUE TITLE
Popups are still the old styled, even in Experimental UI

### ISSUE THREAD

**Issue by isaadansari** [ugo-quaisse/sitecore-author-toolbox#16]
**Is your feature request related to a problem? Please describe.**
Popups are still the old styled, even in Experimental UI. It should look more clean, same goes for buttons.
Looks odd when having different colors.

**Describe the solution you'd like**
Go to Media library and click on the upload multiple files. And see the behavior. 

**Describe alternatives you've considered**
The button color should also  follow the color from the top color picker

**Comment by ugo-quaisse** [comment]
Fixed with last commit https://github.com/ugo-quaisse/sitecore-author-toolbox/commit/c9ded34cba14a82c784df604a38a4bc1a39b6f41
