### ISSUE TITLE
Wider text fields for configuring sites for live URLs

### ISSUE THREAD

**Issue by seanValtech** [ugo-quaisse/sitecore-author-toolbox#20]
**Is your feature request related to a problem? Please describe.**
When configuring URLs for the sites it is difficult to see the whole "Sitecore site path" and "Site URL" as the fields are not long enough.

**Describe the solution you'd like**
The field long enough for these values
Sitecore Path: "/sitecore/content/subdomains/corporatefr/home/"
Site URL: "https://devops-uk.webui.cms-nonprod.xxxx-xxx.com/{nolang}"

**Describe alternatives you've considered**
Another solution could be to hide the "/sitecore/content/" and "https://www." in the fields so that only the most important bit is visible

**Additional context**

![image](https://user-images.githubusercontent.com/50106382/108918099-b907d600-7628-11eb-96f6-253fd127ae0f.png)

**Comment by ugo-quaisse** [comment]
Done in `main` branch
