### ISSUE TITLE
Site Configuration - Option to have Site URL based on both lang and path

### ISSUE THREAD

**Issue by seanValtech** [ugo-quaisse/sitecore-author-toolbox#21]
**Is your feature request related to a problem? Please describe.**
I have an item /sitecore/content/Common/Home/takeaway which for the language version en-gb the live url desired is https://www.site.co.uk/takeaway/ whereas for the en-au language version its https://www.site.com.au/takeaway/ . 

**Describe the solution you'd like**
Add language as an option for setting up sites so something like this could be achieved:
```
    "0": {
      ["/sitecore/content/common/home/", "en-gb"]: "https://www.site.co.uk/%7Bnolang%7D"
    },
    "1": {
      ["/sitecore/content/common/home/", "en-au"]: "https://www.site.com.au/%7Bnolang%7D"
    }
```

The default should be all languages

**Comment by ugo-quaisse** [comment]
Feature is implemented and available in the main branch

**Comment by seanValtech** [comment]
Thank you for implementing the feature, it works perfectly
