### ISSUE TITLE
Support Display Name for Live Url

### ISSUE THREAD

**Issue by seanValtech** [ugo-quaisse/sitecore-author-toolbox#23]
**Is your feature request related to a problem? Please describe.**
When a page has a display name for a language I would like the live url link to include that display name instead of the item name. 

**Additional context**
In this example rather than the path /info/ I would expect /informazioni/

![image](https://user-images.githubusercontent.com/50106382/112147703-ed919200-8bd4-11eb-8ad6-febff9a9a5aa.png)

**Comment by ugo-quaisse** [comment]
<img width="1259" alt="Screenshot 2021-03-24 at 20 09 08" src="https://user-images.githubusercontent.com/54071701/112369745-d50c9f00-8cdc-11eb-9557-bc13fa3fa1f7.png">

**Comment by seanValtech** [comment]
This looks perfect - thank you
