### ISSUE TITLE
"Sitecore Live URL Checking..." is shown when the toggle switch for "↳ Live status" is off

### ISSUE THREAD

**Issue by seanValtech** [ugo-quaisse/sitecore-author-toolbox#24]
**Describe the bug**
When Live URL is on and Live status is off we would expect to only see the Live URL and not the "Sitecore Live URL Checking..." message.

**To Reproduce**
1. Switch Live URL on
2. Switch Live status off
3. View an item which corresponds to a page

**Screenshots**
This shows the Sitecore Live URL Checking...
![image](https://user-images.githubusercontent.com/50106382/112360944-c3ba9700-8cca-11eb-98a3-f868f885e322.png)

**Comment by ugo-quaisse** [comment]
Fixed in last commits
