### ISSUE TITLE
CD Server message won't go away

### ISSUE THREAD

**Issue by catertot** [ugo-quaisse/sitecore-author-toolbox#27]
**Describe the bug**
Each time I navigate to a new item, the same snackbar alert shows up. I hit "Close" and the next time I go to an item, it shows up again. I don't want to set up a CD server and can't figure out how to get that message to go away. I've tried turning off all the options it might be and it still shows up.

**To Reproduce**
I don't really know how to reproduce it.

**Expected behavior**
If I hit "Close", it should remember that I dismissed it and keep it hidden. AND, if possible, it should be clear on the settings how to turn off those suggestions. I don't want to miss out on useful functionality just because of one annoying issue.

**Screenshots**
<img width="616" alt="Screen Shot 2021-04-02 at 9 24 53 AM" src="https://user-images.githubusercontent.com/2622467/113425147-ffbebd80-9396-11eb-84bf-b172bea34a0e.png">

**Comment by ugo-quaisse** [comment]
Hello @catertot , thank you for your bug report.
This issue has been fixed and will be available in version 6.3

**Comment by ugo-quaisse** [comment]
@catertot version 6.2.1 is out, could you please go to chrome://extensions/ and check that you have the latest. If you don't, enable developer mode and clic update

<img width="1659" alt="Screenshot 2021-04-07 at 13 09 11" src="https://user-images.githubusercontent.com/54071701/113857279-9d086000-97a2-11eb-9a0d-cddab578ddd4.png">
