### ISSUE TITLE
Failed to Add to favorites

### ISSUE THREAD

**Issue by imkhairulikhwan** [ugo-quaisse/sitecore-author-toolbox#3]
**Describe the bug**
An error was shown when I clicked Add to favorites for any item in Content Editor

**To Reproduce**
1. Go to Content Editor
2. Click on '/sitecore/client/Applications/ExperienceAnalytics/Dashboard/Conversions/Outcomes/Outcome group/Outcome/PageSettings/KpiChart Parameters'
4. Click Add to favorites
5. Error pops up

**Expected behavior**
Item should be added in the favorite list

**Screenshots**
![image](https://user-images.githubusercontent.com/4214164/80438668-4f029f80-8937-11ea-83fd-4a31d165f998.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044.122

**Comment by ugo-quaisse** [comment]
Fixed and verified. Will be included in the next release (2.1)
