### ISSUE TITLE
Wiki: remove empty pages and dead links

### ISSUE THREAD

**Issue by pbb72** [ugo-quaisse/sitecore-author-toolbox#31]
**Describe the bug**
It's really nice that you have started with a Wiki for the documentation! However, please delete all "empty" pages (those that are only containing a header or the word "soon"), and please remove all links that only point to "#".

Why? Because now your users have to click on a link or open a page to discover there is nothing there. By deleting all those empty pages and dead links, it's immediately clear there is no documentation on the subject yet.

**To Reproduce**
1. Go to https://github.com/ugo-quaisse/sitecore-author-toolbox/wiki
2. Notice the documentation link for "Dark Mode", think "Yes that sounds interesting" and click the link.
3. Wait for the page to load.
4. Read "Soon". 🤨 Notice the last modification date was half a year ago. 😫
5. Go back to the Wiki main page.
6. Notice the link for "Auto switch". Think "I have no idea what that means, let's look it up" and click the link.
7. Notice that nothing happened. Silly me, I must not have clicked well. Click again.
8. No, still nothing happens. Am I asleep? Click.
9. Nothing... Let's try another link. "Extension settings icon" at the bottom sounds interesting, click.
10. Ah! Now something happened. I am offered a new list of links. Wait a moment, "Dark Mode", "Auto switch"? I have returned to the top of the page! 😫
11. Okay, let's try another way. There is another list of "Pages" on the right. Surely, this must be a list of links that actually work?
12. Click the first link, "Character counter".
13. Yes, sure, this link worked. Except all the page contains, is the words "Character counter". Is there actually any content in this Wiki? Start clicking each-and-every-one-of-the-links...
14. Nope. Nothing. All empty. Thanks for wasting my time...

**Expected behavior**
A link is expected to lead to a page that contains information on the link's subject. And a page is expected to contain more than just the title. Or the word "Soon".

**Screenshots**
Shall I include 26 screenshots of empty pages? 😉

**Recommendations**

1. Only create a page when you have actual content to put on the page.
2. Only create a link if you have an actual page to link to, after you've created the page.
3. NEVER use "#" as a placeholder for an empty link. "#" is not non-functional, it actually leads to the top of the current page, which only adds to the confusion. Just use an empty href. Or don't include the href. Or just show the text and don't make it a link. Actually, consider if you really need to show the item, if there is no use to it anyway.
4. Only add links to help pages in your product AFTER you've produced the actual help page, with content.
5. NEVER use non-functional placeholders (of any kind) in a released product. It really confuses your users, and will lower the user trust, even if you release a better product later.

**Comment by ugo-quaisse** [comment]
Wikie has been updated

**Comment by pbb72** [comment]
Better, though I'd say there are still a lot of page that are not helpful. For example "Content Editor Other enhancements" and "Fancy message bars" have no content, and "Extension settings icon" just shows a screenshot of the Launchpad...
