### ISSUE TITLE
HTML editor dissapear

### ISSUE THREAD

**Issue by dbotarman** [ugo-quaisse/sitecore-author-toolbox#39]
When I have Syntax highlighter (Html/Scriban) selected the html editor is not showing, it briefly shows when I click on it but then it seems to be hidden by overlay.
If I use RTE I see the text then clicking on HTML tab I just see a grey box.

**Comment by ugo-quaisse** [comment]
Hello @dbotarman, could you please provide a screenshot? thanks you

**Comment by ghernandez24** [comment]
Hello @ugo-quaisse - To the message above, I am also having the same issue as well where on html editor that content aligns far to the right
![image](https://user-images.githubusercontent.com/78124561/162271176-2531b108-50d0-4893-8ed2-84d738b3884d.png)

**Comment by dbotarman** [comment]
In response to other comment from Guillermo Hernandez, it make sense now there is a huge left margin

Daniel Botha
310-745-5728

**Comment by ugo-quaisse** [comment]
A fix has been pushed with version 6.2.81. This version will be rolled out on the upcoming days.

**Comment by dbotarman** [comment]
Great, thank you!

Daniel Botha
310-745-5728

**Comment by dbotarman** [comment]
Hi,
***@***.***
***@***.***

***@***.***

***@***.***

Thank you.
