### ISSUE TITLE
Not able to click on Data tab

### ISSUE THREAD

**Issue by imkhairulikhwan** [ugo-quaisse/sitecore-author-toolbox#4]
**Describe the bug**

**To Reproduce**
1. Go to /sitecore/client/Applications/ExperienceAnalytics/Dashboard/Conversions/Outcomes/PageSettings/ExperienceAnalyticsFilters Parameters
2. Click on Data tab

Actual behavior:
The tab is not changed even though I clicked on the tab multiple times.

**Expected behavior**
Should be able to click the tab to see the content

**Screenshots**
![Capture](https://user-images.githubusercontent.com/4214164/80670769-63cb6880-8ada-11ea-9130-597180d0766d.PNG)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 81.0.4044.122

**Comment by ugo-quaisse** [comment]
Hi @imkhairulikhwan , can you reproduce it with all items that have a Data tab? or is it only this one?

I cannot reproduce it, can you please send a screenshot with Google Chrome console open (with any error visible)?

Cheers

**Comment by imkhairulikhwan** [comment]
Hi @ugo-quaisse, no I was not able to reproduce it with other items. After refreshing the browser (closed and re-opened), I am able to click the tab now. 

Actually I looked at the console as well before creating the ticket, and it seemed there was no error appeared.

If I face a similar issue again, perhaps I will create/re-open the ticket.

Thank you! :)
