### ISSUE TITLE
[Sitecore 10.2] Error in console

### ISSUE THREAD

**Issue by ErickJensen** [ugo-quaisse/sitecore-author-toolbox#41]
**Describe the bug**
After installing the extension, when navigating to an item in content editor, the content tab is completely blank (no fields or sections whatsoever) and the following error appears in the browser console.

_Error handling response: TypeError: Cannot read properties of undefined (reading 'includes')
    at getHomePath (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/url.js:105:16)
    at getSiteUrl (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/url.js:18:20)
    at initLiveUrl (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/url.js:135:16)
    at sitecoreAuthorToolbox (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/contenteditor.js:70:3)
    at resumeFromWhereYouLeftOff (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/history.js:74:7)
    at chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/toolbox.min.js:1:2848_

I was able to reproduce in both Chrome an Edge browsers with a Sitecore 10.2 instance. **The extension works fine with Sitecore 9.1.1, however**.

**To Reproduce**
1. Install extension.
2. Open Content Editor and navigate to an item.
3. Notice the Content tab is completely blank (no sections or fields show).

**Expected behavior**
I should see sections and fields in the content tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/3577711/176768195-334cd7ca-9485-4bfc-94d5-167f9063b25d.png)

**Comment by cinter** [comment]
I'm getting the same... It worked for a while (just long enough to get excited about this plugin!) but now it's not working anymore:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/58288840/176849661-09247a8a-bbc8-475a-a328-30246b90bbe2.png">

**Comment by cinter** [comment]
Hi Ugo,
Just found out... this is only an issue if the person logged in is NOT an administrator... it all works with no errors when you log in with an administrator account.

If you could figure out what permissions need to be set, could you post those as a work around?

Thank you

**Comment by ugo-quaisse** [comment]
Hello @ErickJensen and @cinter,

I was able to reproduce the issue and fix it locally. As a workaround, can you check that your users have the Item Title Bar and Quick Info Section enabled in their Application Options?

<img width="175" alt="image" src="https://user-images.githubusercontent.com/54071701/177538019-6c32bb89-3b22-44b5-b666-a35164714483.png">


<img width="493" alt="image" src="https://user-images.githubusercontent.com/54071701/177537910-12b7208d-701d-49e9-b6e3-e38febf87950.png">

**Comment by cinter** [comment]
Hi @ugo-quaisse ,
Thanks so much! I have verified those options are enabled. The content does show, but the Info Section Enhancements do not show, and the browser title shows "Resuming..." all the time:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/58288840/177547860-2f217f28-7337-48e1-a696-52dc0f621946.png">

Looking forward to the fix.

**Comment by ugo-quaisse** [comment]
Version 7.1.2 is out, make sure you have the latest version here: chrome://extensions/

Click UPDATE to force the update.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/54071701/178249767-bc661d94-4d71-4896-bba6-147490f866cb.png">
